config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'regions#index'
  resources :regions do
    resources :municipalities, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  protected

  def generate_token
    self.code = loop do
      random_token = SecureRandom.random_number(10000)
      break random_token unless self.class.exists?(code: random_token)
    end
  end
end

app/models/municipality.rb
# == Schema Information
#
# Table name: municipalities
#
#  id         :integer          not null, primary key
#  code       :integer
#  name       :string
#  status     :integer
#  region_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Municipality < ApplicationRecord
  include Tokenable

  belongs_to :region

  validates :name, presence: true

  after_initialize :set_default_status
  enum status: [:active, :inactive]

  def inactive_status
    self.region.municipalities.delete(self)
  end

  private
    def set_default_status              # set status active by default
      self.status ||= :active
    end

    def self.delete_municipalities(municipality_ids)
      municipality_ids.each do |municipality|
        Municipality.find(municipality).delete
      end
    end
end

app/models/region.rb
# == Schema Information
#
# Table name: regions
#
#  id         :integer          not null, primary key
#  code       :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Region < ApplicationRecord
  include Tokenable

  has_many :municipalities
  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_region
  before_action :set_municipalty, only: [:edit, :destroy, :update, :show]

  def new
    @municipality = @region.municipalities.new
  end

  def edit
  end

  def create
    @municipality = @region.municipalities.new(municipality_params)
    if @municipality.save
      flash[:notice] = "The Municipality has been created succesfully"
      redirect_to region_path(@region)
    else
      flash[:alert] = "The Municipality hasn't been created, due an error"
      render :new
    end
  end

  def update
    @municipality.update(municipality_params)
    if params[:municipality][:status] == "inactive"
      @municipality.inactive_status
    end
    if @municipality.save
      flash[:notice] = "The Municipality has been updated succesfully"
      redirect_to region_path(@region)
    else
      flash[:alert] = "The Municipality hasn't been updated, due an error"
      render :edit
    end
  end

  def destroy
    @municipality.destroy
    redirect_to region_path(@region)
  end

  private
    def municipality_params
      params.require(:municipality).permit(:name, :status)
    end

    def set_municipalty
      @municipality = @region.municipalities.find(params[:id])
    end

    def set_region
      @region = Region.find(params[:region_id])
    end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, except: [:index, :new, :create]

  def index
    @regions = Region.all
  end

  def new
    @region = Region.new
  end

  def edit
  end

  def create
    @region = Region.new(region_params)
    if @region.save
      flash[:notice] = "The Region has been created succesfully"
      redirect_to region_path(id: @region.id)
    else
      flash[:alert] = "The Region hasn't been created, due an error"
      render :new
    end
  end

  def update
    @region.update(region_params)
    if params[:region][:municipality_ids].present?
      Municipality.delete_municipalities(params[:region][:municipality_ids])
    end
    if @region.save
      flash[:notice] = "The Region has been updated succesfully"
      redirect_to region_path(id: @region.id)
    else
      flash[:alert] = "The Region hasn't been created, due an error"
      render :new
    end
  end

  def destroy
    @region.destroy
    redirect_to regions_path
  end

  private
  def region_params
    params.require(:region).permit(:name, :municipality_ids)
  end

  def set_region
    @region = Region.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Regions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/municipalities/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= form_for [@municipality.region, @municipality]  do |f| %>
        <% if @municipality.errors.any? %>
          <div id="errors_explanation">
            <h2><%=pluralize(@municipality.errors.count,"error")%> Prohibited this product from being saved:</h2>
            <ul>
            <% @municipality.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control"%>
        </div>
        <% if action == 'edit' %>
          <div class="form-group">
            <%= f.select :status, Municipality.statuses.keys.map { |w| [w.humanize, w] }, {}, { class: "form-control" } %>
          </div>
        <% end %>
        <div class="actions">
          <%= f.submit 'Save', class:"btn btn-primary" %>
          <%= link_to 'Cancel', region_path(@municipality.region), class: 'btn btn-default' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/municipalities/edit.html.erb
<%= render 'form', action: 'edit' %>

app/views/municipalities/new.html.erb
<%= render 'form', action: "new" %>

app/views/regions/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <%= form_for @region do |f| %>
        <% if @region.errors.any? %>
          <div id="errors_explanation">
            <h2><%=pluralize(@region.errors.count,"error")%> Prohibited this product from being saved:</h2>
            <ul>
            <% @region.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control"%>
        </div>
        <div class="form-group">
          <h3>Delete municipalities</h3>
          <%= f.collection_check_boxes(:municipality_ids, @region.municipalities, :id, :name, {include_hidden: false}, {class: 'checkbox'}) %>
        </div>
        <div class="actions">
          <%= f.submit 'Guardar', class:"btn btn-success" %>
          <%= link_to 'Cancelar', regions_path, class: 'btn btn-danger' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/regions/edit.html.erb
<%= render 'form', action: 'edit' %>

app/views/regions/index.html.erb
<div class="container">
  <div class="col-sm-10 col-sm-offset-1">
    <h1 class="text-center">Regions</h1>
    <div class="row">
      <%= link_to "New Region", new_region_path, class:"btn btn-primary" %>
      <table class="table">
        <thead>
          <tr>
            <td>Id</td>
            <td>Code</td>
            <td>Name</td>
            <td>Actions</td>
          </tr>
        </thead>
        <tbody>
          <% @regions.each do |region| %>
            <tr>
              <td><%= region.id %></td>
              <td><%= region.code %></td>
              <td><%= region.name %></td>
              <td><%= link_to 'Show', region_path(region) %> -
                <%= link_to 'Edit', edit_region_path(region) %> -
                <%= link_to 'Delete', region_path(region), method: :delete, data: { confirm: 'Are you sure?' } %> -
                <%= link_to "New Municipality", new_region_municipality_path(region) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/regions/new.html.erb
<%= render 'form', action: 'new' %>

app/views/regions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h2 class="text-center"><%= @region.name %> Municipalities</h2>
      <%= link_to "New Municipality", new_region_municipality_path(@region), class: "btn btn-primary" %>
      <table class="table">
        <thead>
          <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Code</td>
            <td>Status</td>
            <td>Actions</td>
          </tr>
        </thead>
        <tbody>
          <% @region.municipalities.each do |municipality| %>
            <tr>
              <td><%= municipality.id %></td>
              <td><%= municipality.name.humanize %></td>
              <td><%= municipality.code %></td>
              <td><%= municipality.status.humanize %></td>
              <td><%= link_to 'Edit', edit_region_municipality_path(@region, municipality) %> -
                <%= link_to "Delete", region_municipality_path(@region, municipality) , method: :delete, data: { confirm: 'Are you sure?' }%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "Back", regions_path, class: "btn btn-default" %>
    </div>
  </div>
</div>